# Generated by Django 5.2.6 on 2025-09-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dataDeNascimento', models.DateField()),
                ('telefone', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('isbn', models.IntegerField(unique=True)),
                ('editora', models.CharField(max_length=30)),
                ('assunto', models.CharField(max_length=50)),
                ('paginas', models.IntegerField()),
            ],
        ),
    ]
