# Generated by Django 5.2.6 on 2025-09-14 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0002_livro_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='livro_emprestado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_biblioteca.livro'),
        ),
    ]
