# Generated by Django 5.2.6 on 2025-09-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0003_estudante_livro_emprestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.BigIntegerField(unique=True),
        ),
    ]
