# Generated by Django 5.2.6 on 2025-09-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0004_alter_livro_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='telefone',
            field=models.BigIntegerField(),
        ),
    ]
