# Generated by Django 5.2.6 on 2025-09-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0005_alter_estudante_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='assunto',
            field=models.TextField(),
        ),
    ]
