# Generated by Django 5.2.6 on 2025-09-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0006_alter_livro_assunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='assunto',
            field=models.CharField(max_length=50),
        ),
    ]
